import { EventEmitter, SimpleChanges, TemplateRef } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IComponentFormError, IDropdownOption } from '../../interfaces';
import { TranslationService } from '../../services';
import * as i0 from "@angular/core";
export declare class CustomDropdownMultiselectFormComponent {
    parentForm: FormGroup | any;
    controlName: string;
    label?: string;
    labelClass: string;
    dropdownOptionsClass: string;
    dropdownHeaderClass: string;
    dropdownContainerClass: string;
    placeholder: string;
    enableFilter: boolean;
    showClear: boolean;
    options: IDropdownOption[];
    name: string;
    validation: IComponentFormError[];
    disabled: boolean;
    height: string;
    showInactive: boolean;
    emptyOption: string;
    borderRadius: string;
    chipsBelow: boolean;
    wrapChips: boolean;
    itemRemovable: boolean;
    actionButtonText: string;
    actionButtonClicked: EventEmitter<void>;
    valueChange: EventEmitter<IDropdownOption[]>;
    removedItems: EventEmitter<IDropdownOption[]>;
    optionTemplate?: TemplateRef<any>;
    isOpen: boolean;
    filteredOptions: IDropdownOption[];
    customSelectedItems: IDropdownOption[];
    filterText: string;
    translationService: TranslationService;
    set selectedItems(editData: IDropdownOption[]);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    get selectedOptions(): IDropdownOption[];
    getSelectedLabel(option: IDropdownOption): string;
    isSelected(id: any): boolean;
    toggleDropdown(): void;
    sortOptions(): void;
    closeDropdown(): void;
    toggleOptionSelection(option: IDropdownOption): void;
    removeChip(id: string | number, event?: Event): void;
    clearSelection(event: Event): void;
    filterOptions(): void;
    set reset(value: boolean);
    containRequiredError(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomDropdownMultiselectFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomDropdownMultiselectFormComponent, "custom-dropdown-multiselect-form", never, { "parentForm": { "alias": "parentForm"; "required": true; }; "controlName": { "alias": "controlName"; "required": true; }; "label": { "alias": "label"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "dropdownOptionsClass": { "alias": "dropdownOptionsClass"; "required": false; }; "dropdownHeaderClass": { "alias": "dropdownHeaderClass"; "required": false; }; "dropdownContainerClass": { "alias": "dropdownContainerClass"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "enableFilter": { "alias": "enableFilter"; "required": false; }; "showClear": { "alias": "showClear"; "required": false; }; "options": { "alias": "options"; "required": true; }; "name": { "alias": "name"; "required": true; }; "validation": { "alias": "validation"; "required": true; }; "disabled": { "alias": "disabled"; "required": false; }; "height": { "alias": "height"; "required": false; }; "showInactive": { "alias": "showInactive"; "required": false; }; "emptyOption": { "alias": "emptyOption"; "required": false; }; "borderRadius": { "alias": "borderRadius"; "required": false; }; "chipsBelow": { "alias": "chipsBelow"; "required": false; }; "wrapChips": { "alias": "wrapChips"; "required": false; }; "itemRemovable": { "alias": "itemRemovable"; "required": false; }; "actionButtonText": { "alias": "actionButtonText"; "required": false; }; "selectedItems": { "alias": "selectedItems"; "required": false; }; "reset": { "alias": "reset"; "required": false; }; }, { "actionButtonClicked": "actionButtonClicked"; "valueChange": "valueChange"; "removedItems": "removedItems"; }, ["optionTemplate"], never, true, never>;
}
