import { EventEmitter } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IComponentFormError, IDropdownOption } from '../../interfaces';
import { TranslationService } from '../../services';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare class CustomMultiSelectExpandedFormComponent {
    parentForm: FormGroup;
    controlName: string;
    label?: string;
    labelClass: string;
    dropdownOptionsClass: string;
    dropdownHeaderClass: string;
    dropdownContainerClass: string;
    placeholder: string;
    enableFilter: boolean;
    filterDesign: boolean;
    showClear: boolean;
    options: IDropdownOption[];
    name: string;
    validation: IComponentFormError[];
    height: string;
    maxTagsToShow: number;
    expanded: import("@angular/core").WritableSignal<boolean>;
    filteredOptions: IDropdownOption[];
    customSelectedItems: IDropdownOption[];
    filterText: string;
    disabled: boolean;
    disableToggle: boolean;
    chipsBelow: boolean;
    wrapShips: boolean;
    itemRemovable: boolean;
    showSerialWithName: boolean;
    showInactive: boolean;
    disableInactiveSelection: boolean;
    removedItems: EventEmitter<IDropdownOption[]>;
    valueChange: EventEmitter<IDropdownOption[]>;
    set selectedItems(editData: IDropdownOption[]);
    translationService: TranslationService;
    translateService: TranslateService;
    ngOnInit(): void;
    get selectedOptions(): IDropdownOption[];
    getSelectedLabel(option: IDropdownOption): string;
    getSelectedLabels(): string[];
    isSelected(id: any): boolean;
    toggleOptionSelection(option: IDropdownOption): void;
    clearSelection(event: Event): void;
    filterOptions(): void;
    set reset(value: boolean);
    containRequiredError(): boolean;
    removeSelected(id: string | number): void;
    removeSelectedChip(id: string | number): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomMultiSelectExpandedFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomMultiSelectExpandedFormComponent, "custom-multi-select-expanded-form", never, { "parentForm": { "alias": "parentForm"; "required": true; }; "controlName": { "alias": "controlName"; "required": true; }; "label": { "alias": "label"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "dropdownOptionsClass": { "alias": "dropdownOptionsClass"; "required": false; }; "dropdownHeaderClass": { "alias": "dropdownHeaderClass"; "required": false; }; "dropdownContainerClass": { "alias": "dropdownContainerClass"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "enableFilter": { "alias": "enableFilter"; "required": false; }; "filterDesign": { "alias": "filterDesign"; "required": false; }; "showClear": { "alias": "showClear"; "required": false; }; "options": { "alias": "options"; "required": true; }; "name": { "alias": "name"; "required": true; }; "validation": { "alias": "validation"; "required": true; }; "height": { "alias": "height"; "required": false; }; "maxTagsToShow": { "alias": "maxTagsToShow"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "disableToggle": { "alias": "disableToggle"; "required": false; }; "chipsBelow": { "alias": "chipsBelow"; "required": false; }; "wrapShips": { "alias": "wrapShips"; "required": false; }; "itemRemovable": { "alias": "itemRemovable"; "required": false; }; "showSerialWithName": { "alias": "showSerialWithName"; "required": false; }; "showInactive": { "alias": "showInactive"; "required": false; }; "disableInactiveSelection": { "alias": "disableInactiveSelection"; "required": false; }; "selectedItems": { "alias": "selectedItems"; "required": false; }; "reset": { "alias": "reset"; "required": false; }; }, { "removedItems": "removedItems"; "valueChange": "valueChange"; }, never, never, true, never>;
}
