export declare enum AuthConstant {
    TOKEN = "accessToken",
    REFRESH_TOKEN = "refreshToken",
    USER_DATA = "user",
    USER_PERMISSIONS = "permissions",
    USER_ROLES = "roles",
    USER_ROLES_DETAILS = "rolesDetails",
    EXPIRES_AT = "expiresIn"
}
export declare enum UserStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    SUSPENDED = "SUSPENDED"
}
export declare enum Roles {
    ADMIN = "ADMIN",
    SUPER_ADMIN = "SUPER-ADMIN",
    INSPECTOR = "INSPECTOR",
    OPERATOR = "OPERATOR",
    SUPPORT_AGENT = "SUPPORT-AGENT"
}
export declare enum PERMISSIONS {
    all = "all",
    USER_MANAGEMENT_CREATE = "USER-MANAGEMENT:CREATE",
    USER_MANAGEMENT_UPDATE = "USER-MANAGEMENT:UPDATE",
    USER_MANAGEMENT_DELETE = "USER-MANAGEMENT:DELETE",
    USER_MANAGEMENT_VIEW = "USER-MANAGEMENT:VIEW",
    PARKING_ZONE_CREATE = "PARKING-ZONE:CREATE",
    PARKING_ZONE_UPDATE = "PARKING-ZONE:UPDATE",
    PARKING_ZONE_DELETE = "PARKING-ZONE:DELETE",
    PARKING_ZONE_VIEW = "PARKING-ZONE:VIEW",
    POLICIES_CREATE = "POLICIES:CREATE",
    POLICIES_UPDATE = "POLICIES:UPDATE",
    POLICIES_DELETE = "POLICIES:DELETE",
    POLICIES_VIEW = "POLICIES:VIEW",
    ASSETS_CREATE = "ASSETS:CREATE",
    ASSETS_UPDATE = "ASSETS:UPDATE",
    ASSETS_DELETE = "ASSETS:DELETE",
    ASSETS_VIEW = "ASSETS:VIEW",
    VIOLATION_CREATE = "VIOLATION:CREATE",
    VIOLATION_DELETE = "VIOLATION:DELETE",
    VIOLATION_VIEW = "VIOLATION:VIEW",
    VIOLATION_UPDATE = "VIOLATION:UPDATE",
    COMPLAIN_VIEW = "COMPLAIN:VIEW",
    COMPLAIN_UPDATE = "COMPLAIN:UPDATE"
}
