import { ElementRef, AfterViewInit } from '@angular/core';
import * as i0 from "@angular/core";
export declare abstract class CustomTimeBaseComponent implements AfterViewInit {
    hourScrollRef: ElementRef<HTMLDivElement>;
    minuteScrollRef: ElementRef<HTMLDivElement>;
    periodScrollRef: ElementRef<HTMLDivElement>;
    timeInputRef: ElementRef<HTMLInputElement>;
    hours: number[];
    minutes: number[];
    periods: string[];
    selectedHour?: number;
    selectedMinute?: number;
    selectedPeriod: 'AM' | 'PM';
    rangeMin: string;
    rangeMax: string;
    private isDragging;
    private startY;
    private startScrollTop;
    protected itemHeight: number;
    ngAfterViewInit(): void;
    updateItemHeight: () => void;
    get filteredHours(): number[];
    protected getFilteredHoursList(): number[];
    get filteredMinutes(): number[];
    protected scrollToSelectedValues(): void;
    protected to24Hour(hour: number, period: 'AM' | 'PM'): number;
    protected getCenteredIndex(scrollTop: number): number;
    getItemOpacity(index: number, scrollElement: ElementRef<HTMLDivElement> | undefined): number;
    getItemFontWeight(index: number, scrollElement: ElementRef<HTMLDivElement> | undefined): string;
    onHourScroll(): void;
    onMinuteScroll(): void;
    onPeriodScroll(): void;
    onMouseDown(event: MouseEvent, el: HTMLDivElement): void;
    onMouseMove(event: MouseEvent, el: HTMLDivElement): void;
    onMouseUp(el: HTMLDivElement): void;
    protected setTimeFromString(timeStr: string): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomTimeBaseComponent, never>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<CustomTimeBaseComponent, never, never, {}, {}, never, never, true, never>;
}
