import { EventEmitter } from '@angular/core';
import { IDropdownOption } from '../../interfaces';
import { TranslationService } from '../../services';
import * as i0 from "@angular/core";
export declare class CustomMultiSelectComponent {
    label?: string;
    labelClass: string;
    dropdownOptionsClass: string;
    dropdownHeaderClass: string;
    dropdownContainerClass: string;
    placeholder: string;
    enableFilter: boolean;
    showClear: boolean;
    options: IDropdownOption[];
    value: any[];
    height: string;
    showSelectedCountOnly: boolean;
    valueChange: EventEmitter<any[]>;
    isOpen: boolean;
    filteredOptions: IDropdownOption[];
    filterText: string;
    translationService: TranslationService;
    ngOnInit(): void;
    get selectedOptions(): IDropdownOption[];
    getSelectedLabels(): string;
    toggleDropdown(): void;
    toggleOptionSelection(option: IDropdownOption): void;
    isSelected(id: any): boolean;
    clearSelection(event: Event): void;
    filterOptions(): void;
    set reset(value: boolean);
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomMultiSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomMultiSelectComponent, "custom-multi-select", never, { "label": { "alias": "label"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "dropdownOptionsClass": { "alias": "dropdownOptionsClass"; "required": false; }; "dropdownHeaderClass": { "alias": "dropdownHeaderClass"; "required": false; }; "dropdownContainerClass": { "alias": "dropdownContainerClass"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "enableFilter": { "alias": "enableFilter"; "required": false; }; "showClear": { "alias": "showClear"; "required": false; }; "options": { "alias": "options"; "required": true; }; "value": { "alias": "value"; "required": true; }; "height": { "alias": "height"; "required": false; }; "showSelectedCountOnly": { "alias": "showSelectedCountOnly"; "required": false; }; "reset": { "alias": "reset"; "required": false; }; }, { "valueChange": "valueChange"; }, never, never, true, never>;
}
