import { EventEmitter, SimpleChanges } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IComponentFormError, IDropdownOption } from '../../interfaces';
import { TranslationService } from '../../services';
import * as i0 from "@angular/core";
export declare class CustomDropdownFormComponent {
    parentForm: FormGroup | any;
    controlName: string;
    label?: string;
    labelClass: string;
    dropdownOptionsClass: string;
    dropdownHeaderClass: string;
    dropdownContainerClass: string;
    placeholder: string;
    enableFilter: boolean;
    showClear: boolean;
    options: IDropdownOption[];
    name: string;
    validation: IComponentFormError[];
    disabled: boolean;
    height: string;
    showInactive: boolean;
    valueChange: EventEmitter<IDropdownOption | null>;
    isOpen: boolean;
    toggledDropdown: EventEmitter<boolean>;
    selectedOption: IDropdownOption | null;
    filteredOptions: IDropdownOption[];
    filterText: string;
    value: any;
    translationService: TranslationService;
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private setupFormControlSubscription;
    private updateSelectedOptionFromFormValue;
    toggleDropdown(): void;
    closeDropdown(): void;
    writeValue(value: any): void;
    selectOption(option: IDropdownOption): void;
    clearSelection(event: Event): void;
    filterOptions(): void;
    set reset(value: boolean);
    containRequiredError(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomDropdownFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomDropdownFormComponent, "custom-dropdown-form", never, { "parentForm": { "alias": "parentForm"; "required": true; }; "controlName": { "alias": "controlName"; "required": true; }; "label": { "alias": "label"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "dropdownOptionsClass": { "alias": "dropdownOptionsClass"; "required": false; }; "dropdownHeaderClass": { "alias": "dropdownHeaderClass"; "required": false; }; "dropdownContainerClass": { "alias": "dropdownContainerClass"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "enableFilter": { "alias": "enableFilter"; "required": false; }; "showClear": { "alias": "showClear"; "required": false; }; "options": { "alias": "options"; "required": true; }; "name": { "alias": "name"; "required": true; }; "validation": { "alias": "validation"; "required": true; }; "disabled": { "alias": "disabled"; "required": false; }; "height": { "alias": "height"; "required": false; }; "showInactive": { "alias": "showInactive"; "required": false; }; "reset": { "alias": "reset"; "required": false; }; }, { "valueChange": "valueChange"; "toggledDropdown": "toggledDropdown"; }, never, never, true, never>;
}
