import { EventEmitter } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { LoadingService } from '../../services';
import * as i0 from "@angular/core";
export type ConfirmType = 'info' | 'delete' | 'save';
export type ConfirmResult = 'confirm' | 'cancel';
export interface ConfirmOptions {
    message: string;
    modalIcon: string;
    modalTitle: string;
    type: ConfirmType;
    confirmText?: string;
    cancelText?: string;
    extraText?: string;
    successMsg?: string;
    closeOnBackdrop?: boolean;
    autoCloseMs?: number;
}
export declare class CustomConfirmPopupComponent {
    private sanitizer;
    loadingService: LoadingService;
    message: string;
    description: string;
    type: 'info' | 'delete';
    confirmButtonText: string;
    cancelButtonText: string;
    extraButton: string;
    extraInput: boolean;
    confirmEvent: EventEmitter<any>;
    cancelEvent: EventEmitter<void>;
    extraEvent: EventEmitter<void>;
    overlayClicked: EventEmitter<boolean>;
    inputVal: EventEmitter<string>;
    successMsg: import("@angular/core").InputSignal<string>;
    checkedInfoSvg: SafeHtml;
    deleteSvg: SafeHtml;
    checkIcon: SafeHtml;
    inputValue: string;
    currentView: 'confirmation' | 'success';
    successAnimationState: 'hidden' | 'visible';
    successPressed: boolean;
    isVisible: boolean;
    eventVal: any;
    private _showSuccessScreen;
    set showSuccessScreen(value: boolean);
    get showSuccessScreen(): boolean;
    constructor(sanitizer: DomSanitizer, loadingService: LoadingService);
    ngOnInit(): void;
    private watchSuccessScreen;
    ngOnChanges(): void;
    open(event?: any): void;
    close(): void;
    checkSuccess(): void;
    private transitionToSuccess;
    onOverlayClick(event: MouseEvent): void;
    startAnimation(event: any): void;
    doneAnimation(event: any): void;
    inputValueChanged(event: string): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomConfirmPopupComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomConfirmPopupComponent, "custom-confirm-popup", never, { "message": { "alias": "message"; "required": true; }; "description": { "alias": "description"; "required": false; }; "type": { "alias": "type"; "required": true; }; "confirmButtonText": { "alias": "confirmButtonText"; "required": false; }; "cancelButtonText": { "alias": "cancelButtonText"; "required": false; }; "extraButton": { "alias": "extraButton"; "required": false; }; "extraInput": { "alias": "extraInput"; "required": false; }; "successMsg": { "alias": "successMsg"; "required": false; "isSignal": true; }; "showSuccessScreen": { "alias": "showSuccessScreen"; "required": false; }; }, { "confirmEvent": "confirmEvent"; "cancelEvent": "cancelEvent"; "extraEvent": "extraEvent"; "overlayClicked": "overlayClicked"; "inputVal": "inputVal"; }, never, never, true, never>;
}
