import { EventEmitter, ElementRef, AfterViewInit, OnInit, OnDestroy } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IComponentFormError } from '../../interfaces';
import * as i0 from "@angular/core";
export declare class CustomTimeInputFormComponent implements OnInit, AfterViewInit, OnDestroy {
    parentForm: FormGroup;
    name: string;
    controlName: string;
    label: string;
    labelClass: string;
    inputClass: string;
    validation: IComponentFormError[];
    defaultTime: string;
    rangeMin: string;
    rangeMax: string;
    height: string;
    timeChange: EventEmitter<{
        hour: number;
        minute: number;
    }>;
    hourScrollRef: ElementRef<HTMLDivElement>;
    minuteScrollRef: ElementRef<HTMLDivElement>;
    periodScrollRef: ElementRef<HTMLDivElement>;
    private translate;
    dropdownOpen: import("@angular/core").WritableSignal<boolean>;
    hours: number[];
    minutes: number[];
    periods: string[];
    selectedHour: number | string;
    selectedMinute: number | string;
    selectedPeriod: 'AM' | 'PM';
    private itemHeight;
    private isDragging;
    private startY;
    private startScrollTop;
    private currentScrollElement;
    private velocityY;
    private lastY;
    private lastTime;
    private animationFrameId;
    get filteredHours(): number[];
    private getFilteredHoursList;
    get filteredMinutes(): number[];
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    containRequiredError(): boolean;
    toggleDropdown(): void;
    private scrollToSelectedValues;
    private setupScrollListeners;
    private setupDragListeners;
    private onDragStart;
    private onDragMove;
    private onDragEnd;
    private onTouchStart;
    private onTouchMove;
    private onTouchEnd;
    private applyMomentum;
    private snapToNearest;
    private onHourScroll;
    private onMinuteScroll;
    private onPeriodScroll;
    confirmTime(): void;
    setFormValue(): void;
    setExcistValue(): void;
    private setTimeFromString;
    displayTime(): string | null;
    private isTimeInRange;
    private getTimeInHours;
    getItemOpacity(index: number, scrollElement: ElementRef<HTMLDivElement> | undefined, arrayLength: number): number;
    getItemFontWeight(index: number, scrollElement: ElementRef<HTMLDivElement> | undefined): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomTimeInputFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomTimeInputFormComponent, "custom-time-input-form", never, { "parentForm": { "alias": "parentForm"; "required": true; }; "name": { "alias": "name"; "required": true; }; "controlName": { "alias": "controlName"; "required": false; }; "label": { "alias": "label"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "inputClass": { "alias": "inputClass"; "required": false; }; "validation": { "alias": "validation"; "required": false; }; "defaultTime": { "alias": "defaultTime"; "required": false; }; "rangeMin": { "alias": "rangeMin"; "required": false; }; "rangeMax": { "alias": "rangeMax"; "required": false; }; "height": { "alias": "height"; "required": false; }; }, { "timeChange": "timeChange"; }, never, never, true, never>;
}
