import { EventEmitter } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IComponentFormError } from '../../interfaces';
import * as i0 from "@angular/core";
export declare class CustomTimeInputFormComponent {
    parentForm: FormGroup;
    name: string;
    controlName: string;
    label: string;
    labelClass: string;
    inputClass: string;
    validation: IComponentFormError[];
    defaultTime: string;
    rangeMin: string;
    rangeMax: string;
    height: string;
    timeChange: EventEmitter<{
        hour: number;
        minute: number;
    }>;
    dropdownOpen: import("@angular/core").WritableSignal<boolean>;
    hours: number[];
    minutes: number[];
    selectedHour: number | string;
    selectedMinute: number | string;
    selectedPeriod: 'AM' | 'PM';
    get filteredHours(): number[];
    get filteredMinutes(): number[];
    ngOnInit(): void;
    containRequiredError(): boolean;
    toggleDropdown(): void;
    autoSelectMinMinutes(): void;
    confirmTime(): void;
    setFormValue(): void;
    onHourChange(): void;
    autoSelectSingleOptions(): void;
    setExcistValue(): void;
    private setTimeFromString;
    displayTime(): string | null;
    private isTimeInRange;
    private getTimeInMinutes;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomTimeInputFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomTimeInputFormComponent, "custom-time-input-form", never, { "parentForm": { "alias": "parentForm"; "required": true; }; "name": { "alias": "name"; "required": true; }; "controlName": { "alias": "controlName"; "required": false; }; "label": { "alias": "label"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "inputClass": { "alias": "inputClass"; "required": false; }; "validation": { "alias": "validation"; "required": false; }; "defaultTime": { "alias": "defaultTime"; "required": false; }; "rangeMin": { "alias": "rangeMin"; "required": false; }; "rangeMax": { "alias": "rangeMax"; "required": false; }; "height": { "alias": "height"; "required": false; }; }, { "timeChange": "timeChange"; }, never, never, true, never>;
}
